<?php
	// Do not edit this file, rerun gen.php to update!
	class client_set extends collectionSet { }
	
	class client extends genClass
	{
		protected $use_table = "client";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"uuid" => array("type"=>"str","value"=>null),
			"name" => array("type"=>"str","value"=>null),
			"lhash" => array("type"=>"str","value"=>null),
			"phash" => array("type"=>"str","value"=>null),
			"psalt" => array("type"=>"str","value"=>null),
			"reset_code" => array("type"=>"str","value"=>null),
			"reset_expires" => array("type"=>"int","value"=>0),
		);
		public function get_id()
		{
			return $this->get_field("id");
		}
		public function get_uuid()
		{
			return $this->get_field("uuid");
		}
		public function get_name()
		{
			return $this->get_field("name");
		}
		public function get_lhash()
		{
			return $this->get_field("lhash");
		}
		public function get_phash()
		{
			return $this->get_field("phash");
		}
		public function get_psalt()
		{
			return $this->get_field("psalt");
		}
		public function get_reset_code()
		{
			return $this->get_field("reset_code");
		}
		public function get_reset_expires()
		{
			return $this->get_field("reset_expires");
		}
	}
?>