<?php
	// Do not edit this file, rerun gen.php to update!
	class client_rental_set extends collectionSet { }
	
	class client_rental extends genClass
	{
		protected $use_table = "client_rental";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"rental_uid" => array("type"=>"str","value"=>null),
			"clientlink" => array("type"=>"int","value"=>null),
			"Http_Port" => array("type"=>"int","value"=>0),
			"secondbotconfiglink" => array("type"=>"int","value"=>null),
			"expires" => array("type"=>"int","value"=>0),
			"onhold" => array("type"=>"bool","value"=>1),
		);
		public function get_id()
		{
			return $this->get_field("id");
		}
		public function get_rental_uid()
		{
			return $this->get_field("rental_uid");
		}
		public function get_clientlink()
		{
			return $this->get_field("clientlink");
		}
		public function get_Http_Port()
		{
			return $this->get_field("Http_Port");
		}
		public function get_secondbotconfiglink()
		{
			return $this->get_field("secondbotconfiglink");
		}
		public function get_expires()
		{
			return $this->get_field("expires");
		}
		public function get_onhold()
		{
			return $this->get_field("onhold");
		}
	}
?>