<?php
	// Do not edit this file, rerun gen.php to update!
	class message_set extends collectionSet { }
	
	class message extends genClass
	{
		protected $use_table = "message";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"clientlink" => array("type"=>"int","value"=>null),
			"message" => array("type"=>"str","value"=>null),
		);
		public function get_id()
		{
			return $this->get_field("id");
		}
		public function get_clientlink()
		{
			return $this->get_field("clientlink");
		}
		public function get_message()
		{
			return $this->get_field("message");
		}
	}
?>