<?php
	// Do not edit this file, rerun gen.php to update!
	class running_bot_set extends collectionSet { }
	
	class running_bot extends genClass
	{
		protected $use_table = "running_bot";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"secondbotconfiglink" => array("type"=>"int","value"=>null),
			"clientrentallink" => array("type"=>"int","value"=>null),
			"containerid" => array("type"=>"str","value"=>null),
		);
		public function get_id()
		{
			return $this->get_field("id");
		}
		public function get_secondbotconfiglink()
		{
			return $this->get_field("secondbotconfiglink");
		}
		public function get_clientrentallink()
		{
			return $this->get_field("clientrentallink");
		}
		public function get_containerid()
		{
			return $this->get_field("containerid");
		}
	}
?>