<?php
	// Do not edit this file, rerun gen.php to update!
	class second_bot_config_set extends collectionSet { }
	
	class second_bot_config extends genClass
	{
		protected $use_table = "second_bot_config";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"clientlink" => array("type"=>"int","value"=>null),
			"userName" => array("type"=>"str","value"=>null),
			"password" => array("type"=>"str","value"=>null),
			"master" => array("type"=>"str","value"=>null),
			"code" => array("type"=>"str","value"=>null),
			"allowRLV" => array("type"=>"str","value"=>null),
			"homeRegion" => array("type"=>"str","value"=>null),
			"DiscordRelayHook" => array("type"=>"str","value"=>null),
			"discordGroupTarget" => array("type"=>"str","value"=>null),
			"config_uid" => array("type"=>"str","value"=>null),
			"Setting_RelayImToAvatarUUID" => array("type"=>"str","value"=>null),
			"Setting_DefaultSit_UUID" => array("type"=>"str","value"=>null),
			"DiscordFull_Enable" => array("type"=>"str","value"=>null),
			"DiscordFull_Token" => array("type"=>"str","value"=>null),
			"DiscordFull_ServerID" => array("type"=>"str","value"=>null),
		);
		public function get_id()
		{
			return $this->get_field("id");
		}
		public function get_clientlink()
		{
			return $this->get_field("clientlink");
		}
		public function get_userName()
		{
			return $this->get_field("userName");
		}
		public function get_password()
		{
			return $this->get_field("password");
		}
		public function get_master()
		{
			return $this->get_field("master");
		}
		public function get_code()
		{
			return $this->get_field("code");
		}
		public function get_allowRLV()
		{
			return $this->get_field("allowRLV");
		}
		public function get_homeRegion()
		{
			return $this->get_field("homeRegion");
		}
		public function get_DiscordRelayHook()
		{
			return $this->get_field("DiscordRelayHook");
		}
		public function get_discordGroupTarget()
		{
			return $this->get_field("discordGroupTarget");
		}
		public function get_config_uid()
		{
			return $this->get_field("config_uid");
		}
		public function get_Setting_RelayImToAvatarUUID()
		{
			return $this->get_field("Setting_RelayImToAvatarUUID");
		}
		public function get_Setting_DefaultSit_UUID()
		{
			return $this->get_field("Setting_DefaultSit_UUID");
		}
		public function get_DiscordFull_Enable()
		{
			return $this->get_field("DiscordFull_Enable");
		}
		public function get_DiscordFull_Token()
		{
			return $this->get_field("DiscordFull_Token");
		}
		public function get_DiscordFull_ServerID()
		{
			return $this->get_field("DiscordFull_ServerID");
		}
	}
?>